package main

import (
	"fmt"

	_ "github.com/whatap/golib-llm/config"
	_ "github.com/whatap/golib-llm/config/conffile"
	_ "github.com/whatap/golib-llm/io"
	_ "github.com/whatap/golib-llm/lang/pack"
	_ "github.com/whatap/golib-llm/lang/pack/open"
	_ "github.com/whatap/golib-llm/lang/pack/udp"
	_ "github.com/whatap/golib-llm/lang/ref"
	_ "github.com/whatap/golib-llm/lang/service"
	_ "github.com/whatap/golib-llm/lang/step"
	_ "github.com/whatap/golib-llm/lang/value"
	_ "github.com/whatap/golib-llm/lang/variable"
	_ "github.com/whatap/golib-llm/logger"
	_ "github.com/whatap/golib-llm/logger/logfile"
	_ "github.com/whatap/golib-llm/logsink/zip"

	_ "github.com/whatap/golib-llm/net"
	_ "github.com/whatap/golib-llm/net/oneway"
	_ "github.com/whatap/golib-llm/net/udp"
	_ "github.com/whatap/golib-llm/openmx"
	_ "github.com/whatap/golib-llm/util/ansi"
	_ "github.com/whatap/golib-llm/util/bitutil"
	_ "github.com/whatap/golib-llm/util/cmdutil"
	_ "github.com/whatap/golib-llm/util/compare"
	_ "github.com/whatap/golib-llm/util/dateutil"
	_ "github.com/whatap/golib-llm/util/hash"
	_ "github.com/whatap/golib-llm/util/hexa32"
	_ "github.com/whatap/golib-llm/util/hll"
	_ "github.com/whatap/golib-llm/util/hmap"
	_ "github.com/whatap/golib-llm/util/iputil"
	_ "github.com/whatap/golib-llm/util/keygen"
	_ "github.com/whatap/golib-llm/util/list"
	_ "github.com/whatap/golib-llm/util/mathutil"
	_ "github.com/whatap/golib-llm/util/openstack"
	_ "github.com/whatap/golib-llm/util/paramtext"
	_ "github.com/whatap/golib-llm/util/queue"
	_ "github.com/whatap/golib-llm/util/stringutil"
	_ "github.com/whatap/golib-llm/util/urlutil"
	_ "github.com/whatap/golib-llm/util/uuidutil"
	// _ "github.com/whatap/golib-llm/agent/agent/active"
	// _ "github.com/whatap/golib-llm/agent/agent/alert"
	// _ "github.com/whatap/golib-llm/agent/agent/boot"
	// _ "github.com/whatap/golib-llm/agent/agent/config"
	// _ "github.com/whatap/golib-llm/agent/agent/control"
	// _ "github.com/whatap/golib-llm/agent/agent/counter"
	// _ "github.com/whatap/golib-llm/agent/agent/counter/meter"
	// _ "github.com/whatap/golib-llm/agent/agent/countertag"
	// _ "github.com/whatap/golib-llm/agent/agent/data"
	// _ "github.com/whatap/golib-llm/agent/agent/kube"
	// _ "github.com/whatap/golib-llm/agent/agent/pprof"
	// _ "github.com/whatap/golib-llm/agent/agent/secure"
	// _ "github.com/whatap/golib-llm/agent/agent/stat"
	// _ "github.com/whatap/golib-llm/agent/agent/topology"
	// _ "github.com/whatap/golib-llm/agent/agent/trace"
	// _ "github.com/whatap/golib-llm/agent/agent/trace/api"
	// _ "github.com/whatap/golib-llm/agent/alert"
	// _ "github.com/whatap/golib-llm/agent/lang/conf"
	// _ "github.com/whatap/golib-llm/agent/logsink/watch"
	// _ "github.com/whatap/golib-llm/agent/logsink/zip"
	// _ "github.com/whatap/golib-llm/agent/util/crypto"
	// _ "github.com/whatap/golib-llm/agent/util/logutil"
	// _ "github.com/whatap/golib-llm/agent/util/oidutil"
	// _ "github.com/whatap/golib-llm/agent/util/sqlutil"
	// _ "github.com/whatap/golib-llm/agent/util/sys"
)

func main() {
	fmt.Println("Whatap Golang common library")
}
